### ISSUE TITLE
SBA MegaIssue and todo

### ISSUE THREAD

**Issue by NotNemesis** [madoctopus/Turing#217]
I am currently working on SBA and I have many things to implement. As of November 6, 2016, a basic shell of the game is complete, with battling, attacks, characters to select ect. Here are some things I'd like to work on and a sort of timeline for them. The sooner an item gets done, the sooner the other ones begin.

- [ ] Place battle process in a procedure TIME: 1 week (~Nov 14)
A very quick fix. Its just putting the calculations into a procedure.

- [ ] Stylize the game TIME: 1 week (~Nov 14)
This would mean formatting, clearing the screen properly, maybe adding some color or the title screen. This could be done in about an hour. 

- [ ] Adding healing conditionals to the game TIME: 3 weeks (~Nov 28)
This would involve accessing another turing file with a bunch of if structures which check which character and attack was used and what it will do. The hardest part about this is making the program access another file. 

- [ ] Adding status affliction conditionals to the game TIME: 5 weeks (~Dec 12)
This needs item 3 to be done first which is why I gave it a timeline of 5 weeks. It would require putting in a bunch of variables which would add or subtract. 

- [ ] Adding first official character TIME: 6 weeks (~Dec 19)
This will be a major milestone, adding the first official character. There will be some planning but a lot of refining after adding more characters.

- [ ] Character sprites TIME: 6+ weeks (Dec 19+)
At this point, I don't know how long this will take me so I will just put it at 6+ weeks. Character sprites will be on screen moving to simulate hitting each other. I need someone to draw a base model.

- [ ] Character animations TIME: 6+ weeks (Dec 19+)
Add animations to show sword slashes, heals etc.

- [ ] Versus screen TIME: 6+ weeks (Dec 19+)
A screen before the game begins showing the two characters who will be fighting each other

- [ ] Music TIME: 6+ weeks (Dec 19+)
In game music

**Comment by NotNemesis** [comment]
Update:
I'm going to ignore number 2, _stylize the game_, and just move on because the menus will look different anyways and there is no point to changing them now.

I'm making good progress on number 3 and I think I should be done it by this week. I'm currently working on it in branch _SBA-DA1.2.9_ and it won't be merged until I'm done. I'll add a new character that will have healing abilities to test conditionals. 
👌

**Comment by NotNemesis** [comment]
Update:
I am very happy that another thing has been crossed off the list! With the new character, Healdude, you can now heal yourself. There may still be a few bugs with healing but they should be fixed up quickly. 

The next task for me is to add status and attack conditionals. I'm unsure how fast I can do this but I know that many of the ideas I have for this can be easily implemented. Also keep in mind that the attacks added here are the final attacks that appear in the game.

I'd also want to add stat boosts but that again isn't very difficult. 

One thing that I have to fix is the ordering of the calculations. I believe that all the calculations should be complete before telling the player how much damage is actually done, as opposed to the current way where it will tell the player the calculated damage.
